import type { Patient, VitalReading } from "./patient-data";
import { getRiskLevel } from "./patient-data";

function formatVitals(r: VitalReading): string {
  return `HR: ${r.HR} | Temp: ${r.Temp}°C | SpO₂: ${r.O2Sat}% | BP: ${r.SBP}/${r.DBP} | Resp: ${r.Resp} | MAP: ${r.MAP}`;
}

export function generatePatientReport(patient: Patient, currentHour: number): string {
  const reading = patient.readings[currentHour];
  const risk = getRiskLevel(reading.riskScore);
  const now = new Date().toLocaleString();

  const lines: string[] = [];
  lines.push("═".repeat(72));
  lines.push("          SEPSIS EARLY WARNING SYSTEM — CLINICAL REPORT");
  lines.push("═".repeat(72));
  lines.push(`Generated: ${now}`);
  lines.push(`Report Hour: ${currentHour + 1} / ${patient.readings.length}`);
  lines.push("");

  lines.push("─── PATIENT DEMOGRAPHICS ───────────────────────────────────────────");
  lines.push(`Name:            ${patient.name}`);
  lines.push(`Age / Gender:    ${patient.age}y ${patient.gender}`);
  lines.push(`Bed:             ${patient.bed}`);
  lines.push(`Admit Time:      ${patient.admitTime}`);
  lines.push(`Weight / Height: ${patient.weight} kg / ${patient.height} cm`);
  lines.push(`Blood Type:      ${patient.bloodType}`);
  lines.push(`Admit Diagnosis: ${patient.admitDiagnosis}`);
  lines.push(`Comorbidities:   ${patient.comorbidities.join(", ")}`);
  lines.push(`Allergies:       ${patient.allergies.join(", ")}`);
  lines.push("");

  lines.push("─── CURRENT RISK ASSESSMENT ────────────────────────────────────────");
  lines.push(`Risk Score:      ${Math.round(reading.riskScore * 100)}%`);
  lines.push(`Risk Level:      ${risk.label}`);
  lines.push(`Sepsis Label:    ${reading.sepsisLabel ? "POSITIVE" : "Negative"}`);
  lines.push("");

  lines.push("─── CURRENT VITALS ─────────────────────────────────────────────────");
  lines.push(`Heart Rate:      ${reading.HR} bpm`);
  lines.push(`Temperature:     ${reading.Temp} °C`);
  lines.push(`SpO₂:            ${reading.O2Sat} %`);
  lines.push(`Blood Pressure:  ${reading.SBP}/${reading.DBP} mmHg`);
  lines.push(`MAP:             ${reading.MAP} mmHg`);
  lines.push(`Resp Rate:       ${reading.Resp} /min`);
  lines.push("");

  lines.push("─── ACTIVE TREATMENTS ──────────────────────────────────────────────");
  const activeAtHour = patient.treatments.filter(t => t.startHour <= currentHour + 1 && t.status !== "discontinued");
  if (activeAtHour.length === 0) {
    lines.push("  No active treatments at this hour.");
  } else {
    lines.push(`  ${"Medication".padEnd(28)} ${"Dose".padEnd(18)} ${"Route".padEnd(8)} Frequency`);
    lines.push("  " + "─".repeat(68));
    for (const t of activeAtHour) {
      lines.push(`  ${t.name.padEnd(28)} ${t.dosage.padEnd(18)} ${t.route.padEnd(8)} ${t.frequency}`);
    }
  }
  lines.push("");

  lines.push("─── CLINICAL TIMELINE ──────────────────────────────────────────────");
  const eventsUpToNow = patient.clinicalEvents.filter(e => e.hour <= currentHour + 1);
  for (const e of eventsUpToNow) {
    const tag = `[Hr ${String(e.hour).padStart(2)}] [${e.type.toUpperCase().padEnd(10)}]`;
    lines.push(`  ${tag} ${e.description}${e.value ? " — " + e.value : ""}`);
  }
  lines.push("");

  lines.push("─── VITAL SIGN TREND (Last 12 hours) ───────────────────────────────");
  const start = Math.max(0, currentHour - 11);
  lines.push(`  ${"Hour".padEnd(6)} ${"HR".padEnd(8)} ${"Temp".padEnd(8)} ${"SpO₂".padEnd(8)} ${"BP".padEnd(12)} ${"Resp".padEnd(8)} Risk`);
  lines.push("  " + "─".repeat(62));
  for (let i = start; i <= currentHour; i++) {
    const r = patient.readings[i];
    const riskPct = Math.round(r.riskScore * 100) + "%";
    lines.push(`  ${String(r.hour).padEnd(6)} ${String(r.HR).padEnd(8)} ${String(r.Temp).padEnd(8)} ${String(r.O2Sat).padEnd(8)} ${(r.SBP + "/" + r.DBP).padEnd(12)} ${String(r.Resp).padEnd(8)} ${riskPct}`);
  }
  lines.push("");
  lines.push("═".repeat(72));
  lines.push("  This report was generated by the AI-powered Sepsis Early Warning");
  lines.push("  System. It is intended for clinical decision support only.");
  lines.push("═".repeat(72));

  return lines.join("\n");
}

export function downloadReport(patient: Patient, currentHour: number) {
  const content = generatePatientReport(patient, currentHour);
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${patient.name.replace(/\s+/g, "_")}_Report_Hr${currentHour + 1}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
